[frontend]
ec2-1 ansible_host=51.20.191.132 ansible_user=ubuntu ansible_private_key_file=~/project-terraform-ansible/terraform/terraform-key-001.pem
ec2-2 ansible_host=16.170.239.146 ansible_user=ubuntu ansible_private_key_file=~/project-terraform-ansible/terraform/terraform-key-001.pem
